# Generated by Django 2.2.19 on 2022-06-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220616_1522'),
        ('posts', '0003_auto_20220616_2339'),
    ]

    operations = [
    ]
